name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Initialize apictl and deploy
      env:
        DEV_ENV: dev
        API_DIR: /home/runner/work/wso2-apim-cicd-apis/wso2-apim-cicd-apis/SwaggerPetstore
        DEV_APIM_HOST: 104.42.181.226
        APIM_ADMIN_USERNAME: ${{ secrets.APIM_ADMIN_USERNAME }}
        API_ADMIN_PASSWORD: ${{ secrets.API_ADMIN_PASSWORD }}
      run: |
        echo 'Initializing apictl'   
        tar -xvzf apictl-3.0.1-linux-i586.tar.gz
        ./apictl/apictl
        export PATH=${PATH}:/home/runner/work/wso2-apim-cicd-apis/wso2-apim-cicd-apis/apictl/
        apictl add-env -e dev \
        --registration https://$DEV_APIM_HOST:9443/client-registration/v0.15/register \
        --apim https://$DEV_APIM_HOST:9443 \
        --token https://$DEV_APIM_HOST:8243/token
        apictl list envs
        echo 'Deploying the API to $DEV_ENV'  
        ls /home/runner/.wso2apictl/exported/apis/ 
        apictl login $DEV_ENV -u $APIM_ADMIN_USERNAME -p $API_ADMIN_PASSWORD -k
        apictl import-api -f $API_DIR -e $DEV_ENV -k --preserve-provider --update --verbose 
         
       
